#:kivy 2.1.0
#:import dp kivy.metrics.dp

<ChatBlock>:
    size_hint_y: None
    height: label.texture_size[1] + 20  # Add some padding
    BoxLayout:
        Label:
            id: label
            text: root.block.prompt if root.block else "No data"
            text_size: self.width, None
            size_hint_y: None
            height: self.texture_size[1]
            padding: [10, 10]
            background_normal: ""
            canvas.before:
                Color:
                    rgba: self.parent.parent.background_color
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [6, 6, 6, 6]

<ChatArea>:
    MDBoxLayout:
        id: box
        orientation: 'vertical'
        spacing: 10  # Add spacing between chat blocks
        adaptive_height: True

ChatScreen:
    name: 'chat_screen'
    MDBoxLayout:
        orientation: 'vertical'
        ChatArea:
            id: chat_area
        MDBoxLayout:
            adaptive_height: True
            MDTextField:
                id: chat_input
                hint_text: "Type a message..."
                multiline: False
                size_hint_x: 0.8
            MDIconButton:
                icon: "send"
                on_release: root.send(chat_input.text)
            MDIconButton:
                icon: "arrow-right"
                on_release: root.continue_game()
            MDIconButton:
                icon: "autorenew"
                on_release: root.retry()
